"""Initial migration.

Revision ID: 531f742487dc
Revises: 
Create Date: 2024-01-16 17:21:42.039204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531f742487dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_block_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stemplate'
    )
    with op.batch_alter_table('token_block_list', schema='stemplate') as batch_op:
        batch_op.create_index(batch_op.f('ix_stemplate_token_block_list_jti'), ['jti'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='stemplate'
    )
    with op.batch_alter_table('users', schema='stemplate') as batch_op:
        batch_op.create_index(batch_op.f('ix_stemplate_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='stemplate') as batch_op:
        batch_op.drop_index(batch_op.f('ix_stemplate_users_id'))

    op.drop_table('users', schema='stemplate')
    with op.batch_alter_table('token_block_list', schema='stemplate') as batch_op:
        batch_op.drop_index(batch_op.f('ix_stemplate_token_block_list_jti'))

    op.drop_table('token_block_list', schema='stemplate')
    # ### end Alembic commands ###
